* Tiny interpreter for the syn language
This is an interpreter i wrote in javascript because i had a sudden realization that programming languages are just text.
what truly makes a programming language is the interpreter. and an interpreter is just a program that takes in text and
processes it. so i thought "i can do that". so i did!

syn stands for synonym because i want to try and make all the keywords be weird synonyms.


** Current features
*** Variable declaration with `make`.
*** Printing text with `say`.
*** Basic math: `+ - * /` (using a stack-based evaluator).
- It uses **postfix notation** for math expressions (`2 3 +` instead of `2 + 3`). I like how strange it looks.
*** Error reporting with line and column numbers
    - Unknown variables
    - Unterminated strings
    - Syntax errors in declarations
    - Division by zero
    - Math on non-numbers

** Example:
#+begin_src
make x = 3
make y = 6 2 x * +
say "The result is " y
#+end_src

This should print `The result is 12` (6 2 x * + in postfix is the same as 6 + (2 * x))

** How to run:
- 1. run synInterpreter.js with node
- 2. pass in a a file ending in ".syn" an argument
#+begin_src bash
  node synInterpreter.js program.syn
#+end_src

*** Alternatively:
- 1. Open `synInterpreter.js` in your editor.
- 2. Edit the code inside the `run(`...`)` call at the top.
- 3. Run the file with node.

#+begin_src bash
  node synInterpreter.js
#+end_src
